CREATE TABLE rewards (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	points INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
